services:
  postgres:
    image: postgres:17
    container_name: signal_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD:
      POSTGRES_DB: signaldb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: @gmail.com
      PGADMIN_DEFAULT_PASSWORD:
    ports:
      - "5050:80"
    networks:
      - my-network
    restart: always

  app:
    container_name: crypto_signal_sweep
    build: .
    depends_on:
      - postgres
    environment:
      - TELEGRAM_TOKEN=
      - TELEGRAM_CHAT_ID=
      - DB_ENABLED=true
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=signaldb
      - DB_HOST=signal_db
      - DB_PORT=5432
      - PAIRS=BTC/USDT,ETH/USDT,SUI/USDT,DOGE/USDT,ADA/USDT,XRP/USDT
      - TIMEFRAMES=15m,1h
      - USE_HIGHER_TF_CONFIRM=false
    networks:
      - my-network
    restart: always

volumes:
  pgdata:

networks:
  my-network:
    external: true
    name: all_dockers
